### PR TITLE
Fix inactive rights editing bug, Take two

### LINKED ISSUE #775: Edit Work that has inactive rights.
### Descriptive summary
Editing a work that has inactive rights will force a user to either cancel the edits or select a rights statement from the list of active rights.

CC HEAD.

### Expected behavior
Edit the metadata of a work without having to choose a new rights statement.

### Actual behavior
Editting the metadata requires selection of a currently active rights statement.  In the case of legacy Works, this will require the user to change the rights from what was originally granted for the Work.

### Steps to reproduce the behavior

1. Create Work
1. Set rights selection to an rights statement with active: false. (via rails console)
1. Edit the Work

### Related work
This is a consequence of #767.  The contributor neglected to bring this issue to light or have a solution for it at the time of the PR.  Not going to name any names, but it was me.

### PR DESCRIPTION
**Pull request by mbklein**
Fixes #775 ; refs #811 and #812

Allows a user to save their edits without altering their rights or removing the inactive ones.

Changes proposed in this pull request:

* the addition of a `MultiValueSelectInput` input class that presents individual drop-down select elements for multi-valued fields 
* the addition of a helper that ensures that current values are always selectable, even if marked inactive by the controlling authority

@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by mbklein** [comment]
@projecthydra/sufia-ui-ux-advisors This PR keeps the look and feel of the form as they were before #811, while fixing the bug it was designed to fix. @grosscol suggested that you might want to advise on whether multi-valued controlled fields would better be served by a single, HTML-standard `<select multiple="true">` component.

File: app/services/rights_service.rb [hunk 1]
```diff
@@ -2,15 +2,33 @@ module RightsService
...
   def self.label(id)
     authority.find(id).fetch('term')
   end
 
   def self.active_elements
     authority.all.select { |e| authority.find(e[:id])[:active] }
   end
+
+  def self.inactive_elements
+    authority.all.select { |e| authority.find(e[:id])[:active] == false }
```
Comment (jcoyne) [inline app/services/rights_service.rb]: Is there some reason you aren't doing `.reject { |e| authority.find(e[:id])[:active] }`?

File: app/services/rights_service.rb [hunk 2]
```diff
@@ -2,15 +2,33 @@ module RightsService
...
+
+  def self.select_active_options
     active_elements.map { |e| [e[:label], e[:id]] }
   end
 
+  def self.active?(id)
+    authority.find(id).fetch('active')
+  end
+
+  def self.select_inactive_options
```
Comment (jcoyne) [inline app/services/rights_service.rb]: Is this method ever used? If not, can we get rid of it?

File: app/services/rights_service.rb (hunk 1 above)
Comment (justcolin) [inline app/services/rights_service.rb]: Sorry, accidentally deleted a comment by @jcoyne. He said:

Is there some reason you aren't doing `.reject { |e| authority.find(e[:id])[:active] }`?

File: app/services/rights_service.rb (hunk 2 above)
Comment (mbklein) [inline app/services/rights_service.rb]: Ah, it's a remnant of the original fix that got refactored out. It can go.

File: app/services/rights_service.rb (hunk 1 above)
Comment (mbklein) [inline app/services/rights_service.rb]: Fair point. :+1:

**Comment by mbklein** [comment]
We'll also fix the rubocop complaints before we push again.

**Comment by justcolin** [comment]
The `MultiValueSelectInput` stuff looks good to me.

**Comment by mjgiarlo** [comment]
Looks good to me! @tpendragon @jcoyne @escowles
