### PR TITLE
Fix work presenter's solr query to get all file set ids, fixes #1136

### LINKED ISSUE #1136: SystemStackError in work_show_presenter
looks like this: 
```
SystemStackError (stack level too deep):
  app/views/curation_concerns/base/show.html.erb:16:in `_app_views_curation_concerns_base_show_html_erb___3900729328614262446_70171586185720'
```

Turns out solr is only returning 10 file sets so if your representative_id is not one of  those 10 the presenter thinks it's not a file set and keeps trying to drill down to get the file set.

patch forthcoming

### PR DESCRIPTION
**Pull request by hackmastera**
@projecthydra/sufia-code-reviewers

### CODE REVIEW

File: spec/presenters/curation_concerns/work_show_presenter_spec.rb [hunk 1]
```diff
@@ -93,6 +93,20 @@
       end
     end
 
+    context "when there are >10 file sets" do
+      before do
+        12.times do
+          fs = create(:file_set)
```
Comment (hackmastera) [inline spec/presenters/curation_concerns/work_show_presenter_spec.rb]: Sure, that would reduce the scope of the test and assume the indexing piece is tested sufficiently elsewhere.
